POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alice",
    "number": 123456
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alice"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 123456
}